# preload=/home/avesek/Pictures/Camera/anime2.png
# wallpaper=eDP-1:/home/avesek/Pictures/Camera/anime2.png

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Camera/anime2.png
    fit_mode = cover
}
