set -g default-terminal "screen-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
unbind '"'

bind -n M-v split-window -h
bind -n M-V split-window -v

unbind r
bind r source-file ~/.tmux.conf

# Switch panes using Alt + h/j/k/l without prefix
bind -n M-h select-pane -L   # Alt + h → move to left pane
bind -n M-j select-pane -D   # Alt + j → move to bottom pane
bind -n M-k select-pane -U   # Alt + k → move to top pane
bind -n M-l select-pane -R   # Alt + l → move to right pane

# Resize panes using Alt + H/J/K/L without prefix
bind -n M-H resize-pane -L 5   # Alt + Shift + h → resize left
bind -n M-J resize-pane -D 5   # Alt + Shift + j → resize down
bind -n M-K resize-pane -U 5   # Alt + Shift + k → resize up
bind -n M-L resize-pane -R 5   # Alt + Shift + l → resize right

bind -n M-m resize-pane -Z

# Bind Ctrl + j / Ctrl + k to switch between windows (workspaces)
bind -n C-j next-window
bind -n C-k previous-window

# Create new workspace with Ctrl + c
bind -n C-n new-window

# Rename workspace with Ctrl + ,
unbind-key ,
bind -n "C-r" command-prompt -I "#W" 'rename-window "%%"'

# Close (kill) current workspace with Ctrl + q
bind -n C-q kill-window

# close (kill) current plane with alt + q
bind -n M-q kill-pane


set -g mouse on

set-window-option -g mode-keys vi

bind v copy-mode \; send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse 

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'jimeh/tmux-themepack' # to configure tmux theme
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

set -g @themepack 'powerline/default/cyan' # use this theme for tmux

set -g @resurrect-capture-pane-contents 'on' # allow tmux-ressurect to capture pane contents
set -g @continuum-restore 'on' # enable tmux-continuum functionality

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

